### ISSUE TITLE
[bug] /opt/node_n/bin/n: line 555: node: command not found

### ISSUE THREAD

**Issue by nqb** [YunoHost/issues#1259]
YunoHost 3.3.3

Yesterday at 6:25, I received following mail at `root@my.domain`:
```
/etc/cron.daily/node_update:

                                                                           0.2%
                                                                           0.8%
#                                                                          2.7%
####                                                                       6.3%
######                                                                     8.7%
##########                                                                14.2%
###########                                                               16.5%
##############                                                            20.5%
################                                                          22.9%
###################                                                       27.4%
#######################                                                   32.0%
#########################                                                 34.9%
############################                                              39.1%
##############################                                            42.9%
#################################                                         45.9%
###################################                                       49.4%
######################################                                    52.9%
########################################                                  56.3%
##########################################                                58.4%
############################################                              61.8%
###############################################                           65.6%
#################################################                         69.2%
####################################################                      72.9%
#######################################################                   76.5%
############################################################              84.1%
#################################################################         91.1%
######################################################################    97.7%
######################################################################## 100.0%
/opt/node_n/bin/n: line 555: node: command not found
```

Content of `/opt/node_n/node_update.log`:
```
[..]
Wed Dec 26 06:25:02 CET 2018
Update of the version 6
Thu Dec 27 06:25:04 CET 2018
Update of the version 6

     install : node-v6.16.0
       mkdir : /opt/node_n/n/versions/node/6.16.0
       fetch : https://nodejs.org/dist/v6.16.0/node-v6.16.0-linux-x64.tar.gz
   installed :
[..]
```

**Comment by Psycojoker** [comment]
Hello,

YunoHost core doesn't provide nodejs by default. This is very likely coming from an application you have installed (and could be a bug in a nodejs helper).

Could you provide the application you have installed AND removed plz? (remove is important because it might be a application that doesn't correctly remove nodejs after having installed it) You can list the installed application using `yunohost app list -i`.

Thanks for taking the time to open a ticket <3

**Comment by nqb** [comment]
```yaml
apps: 
  0: 
    description: Framapad clone, a online editor providing collaborative editing in real-time.
    id: etherpad_mypads
    installed: True
    label: Etherpad Mypads
    license: Apache-2.0
    name: Etherpad Mypads
  1: 
    description: Kanboard is a simple visual task board web application
    id: kanboard
    installed: True
    label: Kanboard
    license: AGPL-3.0
    name: Kanboard
```
