### ISSUE TITLE
"yunohost app list" UX is bad

### ISSUE THREAD

**Issue by Psycojoker** [YunoHost/issues#1389]
Since the beginning of using YunoHost I've never liked the fact that "yunohost app list" return available apps to be installed and that you need to do a "yunohost app list -i" to see the installed apps.

Recently I saw that I wasn't the only one really disliking that and also see that it was not intuitive at all. Also the output of "yunohost app list -i" is not very practical and though for human usage, rather for the distant api.

So I'm suggesting those changes:

1. add "yunohost app installed" and "yunohost app available" (or something similar if you have better suggestions, I don't have strong opinions on that)
2. make "yunohost app list" display those 2 commands to inform the user about this change.
3. currently "yunohost app list -i" display this kind of result

```yaml
apps:              
  0:                                                                             
    description: Système de page de status open-source
    id: cachet     
    installed: True
    label: Cachet                                 
    license: BSD-3-Clause
    name: Cachet   
  1:                                                                   
    description: Clone de Framapad, un éditeur en ligne fournissant l’édition collaborative en temps réel.
    id: etherpad_mypads
    installed: True       
    label: Etherpad FpSource                      
    license: Apache-2.0
    name: Etherpad Mypads
  2:                                             
    description: Une forge git légère
    id: gitea          
    installed: True        
    label: Gitea                                               
    license: MIT 
    name: Gitea    
```

This is really not that great at all for users, we probably want to switch to something like that (open suggestion, don't hesitate to suggest better solutions):

```yaml
cachet:
  label: Cachet
  description: Système de page de status open-source
  location: cachet.mydomain.org
etherpad_mypads:
  local_label: Etherpad FpSource                      
  name: Etherpad Mypads
  description: Clone de Framapad, un éditeur en ligne fournissant l’édition collaborative en temps réel.
  location: mydomain.org/pad
```

I'm pretty sure that there is quite other commands for which we could change the CLI api because they are bad :/
