### ISSUE TITLE
Specification draft for vulnerabilities indexing and detection ?

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1438]
Regularly, we hear about CVEs affecting system packages or apps that may be installed. It would be nice to have a way for Yunohost to automatically diagnose new vulnerabilities and warn the admin about them.

To do so, I propose the following. Similarly to apps.json, the project could publish and maintain a security_issues.json or .yml that describe system packages and apps version that are affected by some vulnerabilities.

For example it could contain : 

```yaml
system:
   - package: "dovecot"
     versions: "< 2.2.27-3+deb9u5"
     infos: "https://www.debian.org/security/2019/dsa-4510"
     level: "important"
   - package: "foo"
     versions: "< 1.2.3+deb9u5"
     infos: "https://example.com/emaged-foo-is-broken"
     level: "warning"
apps:
   - app: "jirafeau"
     versions: "< 1.4~ynh1"
     infos: "https://github.com/yunohost-apps/jireafeau_ynh/issues/666"
     level: "warning"
```

Yunohost's core would regularly (e.g. every day) fetch this json/yaml file and analyze if it find a corresponding vulnerability, in turn triggering a critical error that gets reported by email or other means of notification. This can be integrated easily in the upcoming diagnosis system.
