### ISSUE TITLE
Thoughts towards a new packaging format / manifest format

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1614]
In the past years, a lot has been done to support a large scope of action (backup/restore, change_url, config panel, ...) and aspects (e.g. fail2ban, logrotate, dedicated user, ...) and to increase the overall robustness by creating and iterating over the helpers that act as an abstraction layer that can be fixed/improved for all apps at once.

However, apart from the helpers and formatting of scripts, the current format is pretty much at a stop despite the fact that : 
- many apps perform the same kind of tests/manipulations all over the place (typically `test -e /var/www/$app`, or registering all answers from the install form as settings)
- many details or actions such as checking if the version number is different during an upgrade (c.f. Josue's PR) or performing a safety backup before an upgrade should be handled by the core as this practice should be the case for 99% of apps.
- many information are written in the app's README (like unsupported archs, known limitations, demo website, ..) and we expect people to go read it even though these could be formalized.

All of these increase the maintenance cost of applications (or decrease / limit what we can do in terms of UX) and we have more than a hundred apps level 4+ nowadays and it's not really viable on the long term.

So here I'm discussing possible improvements for the manifest (though it has implications in other parts of the packaging format)

### General notes

- This is related to https://github.com/YunoHost/issues/issues/1606 since it's a discussion on how to make the app package evolve, and to go towards a declarative format, but it remains pretty much independent
- This is still brainstorming/heavy draft
- The proposed changes would be breaking changes as in "we'll shall bump the packaging_version key to 2"
- The proposed changes are important, but in terms of transitioning from the old to the new format, I'm confident that a good 90% of it could be automatically performed by a script for all apps such that you'd basically only have to re-run the CI to validate that the auto-refactoring of the app did a good job
- I wrote this draft in the TOML syntax, mainly because it would make sense on the long term to keep a single syntax format between the manifest and config panel, and its syntax seems lighter than json overall (though some details are not 100% straightforward)
- The following sections goes through [this entire draft here](https://paste.yunohost.org/raw/galuwizote). The most important section to be discussed is `[resources]` and its implications

### Manifest: general infos

This is the part where we define the general info like id, name. Pretty much the same as current json format (only in toml here). Except that for the description I only have the english version - which re-raise the question of internationalization (c.f. mechanism from Bram). But same question applies to current config panel ...

```toml
name = "Hello World"
id = "helloworld"
packaging_format = 2.0
version = "0.1~ynh1"
description = "A dummy basic app to illustrate YunoHost's app packaging."

[maintainer]
name = "alexAubin"
email = "aleks@foo.bar"
```

### Manifest: upstream infos

Not life changing, but it's always been confusing if the `license` key or `url` key was about the yunohost app or upstream ... and there are in fact many info we may want to provide about the upstream like the site/landpage, the demo, the code repository, or the documentation.

```toml
[upstream]
license = "WTFPL"
site = "https://foo.com"
demo = "https://demo.foo.com"
code = "https://github.com/foo/foo"
userdoc = "https://doc.foo.com"
```

### Manifest: integrations between the app and Yunohost

This is something you'd typically have to lookup in the README to know : wether or not the app is integrated with Yunohost's LDAP and SSO (two related but different aspects) and we should be able to tell the user about it. Similarly we should be able to tell the user before the app install wether the app supports backup/restore, change_url, etc... all of these can be guessed from the corresponding script so it depends whether we want

```toml
[integration]
ldap = true            # true/false if yunohost credentials can be used to login or "not_relevant" if there's no notion of account
sso = false            # true/false if users are autologged via the SSO or "not_relevant" if there's no notion of account
multi_instance = false # true/false or "not_relevant"

# could also add: backup/restore, change_url, config panel, ... but usually the fact that script exists is enough but it all depends wether we want to make it explicit/implicit
# could also add: fail2ban (though could also derive it from the presence of fail2ban helpers in scripts...)
```

### Manifest: requirements

That one is a bit more interesting: so far we only require a yunohost version, but we should be able to test other things like architecture (currently the user has to launch the install then wait for it to fail miserably - or read the README to learn it). Also indications of system resources required can be nice to avoid launching on a RPi an app that will require 3GB of RAM to compile half of the nodejs ecosystem.

```toml
[requirements]
yunohost = ">= 3.6.0"
unsupported_archs = ["arm*", "i386"]

   [requirements.install]             # Yunohost will refuse to install if this is not met
   ram_and_swap = "500M"              # sometimes this requirement can be high because of builds during install etc

   [requirements.usage]               # This is mostly meant to give a *rough* estimate to the user
   ram_and_swap = "50M"               # of the memory/disk usage after app is installed
```

### Manifest: resources

This is the part that has the most complex/powerful implications. Currently an app will start by creating/booking a bunch of resources. Here "resources" means something like a port, a webpath, an installation folder, a system user, a database, etc ... and each time will create/register a setting out of this. This in turns lead to significant portion of duplicated boring code (e.g. checking `/var/www/$app` will also happen in restore script) and/or failure of the script that could be identified much earlier by the core (e.g. booking a webpath already registered).

Currently, the hack includes a hack to detect webpath conflict before running the script, but that remains a hack that is not applicable to other resources. Having declarativeness also unlock many possibilities, like automatically knowing that a backup of a DB should be done during backup steps, or could help with computing the disk usage of a specific app.

In the proposed system, declaring a "resources" would : 
- book/provision anything that needs to be booked/provisioned *before* the actual app script is launched. Typically finding a free port, or checking the install path /var/www/$app is available. All of these using the existing helpers.
- some of these like `webpath` will corresponds to the usual questions about domain/path and register the corresponding web path
- generate and register some settings that will be loaded inside the app script. So for example [all of these lines](https://github.com/YunoHost-Apps/helloworld_ynh/blob/master/scripts/install#L18-L48) would become obsolete (same kind of stuff for other scripts).
- if a resources is added later during the package life, it can be automatically provisioned and the corresponding settings defined at the appropriate time before running the upgrade script (so no more checking "if a setting is not defined, create it with some default value etc.")

Here an example for various typical resources types that could be handled:
```toml
[resources]   


  [resources.port]           # This will find a free port using ynh_find_port
  type = "port"
  exposure = "internal"      # Could also be a "public" such that the port will be allowed on firewall
  default = 1234


  [resources.final_path]     # This will make sure that /var/www/{{app}} is available 
  type = "folder"
  default = "/var/www/{{app}}"


  [resources.webpath]        # This will generate default questions about "domain" and "path",
  type = "webpath"           # check/book the path, and create corresponding setting
  full_domain = true
  default = "{{maindomain}}/{{app}}"


  [resources.secret_token]   # This will greate a random string setting using ynh_random_string
  type = "random_string"
  length = 12


  [resources.user]           # This will provision a system user name "{{app}}" by default
  type = "system_user"


  [resources.db]             # This will provision a mysql DB "{{app}}" by default and create settings "db_name", "db_user", "db_pwd". Should also handle postgresql and mongodb or others.
  type = "db_mysql"

  # possibly other things, to be discussed (provisioning the db before install script is already pretty advanced)
```

### Upgrade behavior

This is kinda unrelated to the manifest format itself (ugh maybe should create another issue but meh :|) 

Just like the management of upgrade version (no need to upgrade if version is not different, c.f. Josue's PR), maintaining the [safety-backup-before-upgrade](https://github.com/YunoHost/example_ynh/blob/master/scripts/upgrade#L64-L77) through the same snippet in every app is costly (and messy, c.f. the upgrade logs, in particular the failed upgrades) and should anyway be the default behavior for all apps. We can make this the default behavior for apps using packaging_format >= 2.

### Displaying notes to the admin before/after performing an action

This is kinda unrelated to the manifest format itself (ugh maybe should create another issue but meh :|) 

Currently we have many situations where : 
- we want to inform the admin about known limitations of the app *before* running the install 
- we want to give pieces of information to the admin *after* running the install (like credentials or remaining instructions)
- we want to give pieces of information to the admin *after* running the upgrade (c.f. nextcloud about modules that possibly got disabled and needs to be reenabled)

Not sure about the first case, I'm thinking we could have a 

```toml
[install.notes_before]
foo = "This app only works with Firefox"
bar = "This app relies on google analytics"
```

For the other case: the pieces of information we want to give the admin *after* a script ran heavily depends of what happened inside the script. The current practice is usually to send an email to the admin (assuming it'll be found ...) but nowadays we could use the `$YNH_RETURN` variable as already done in the config panel. Therefore the text / infos could be caught this way by the core and displayed in an appropriate way right after the install/upgrade finished

**Comment by alexAubin** [comment]
Doing another iteration of self-brainstorming because I intend to start working on this for 4.2. Made the following tweaks compared to what I discussed earlier : 
- wrap "version", "maintainer", "requirements and "integration" inside a bigger "package" section
- add "disclaimer" key
- remove 'ask' strings for domain/path/admin/is_public type args (they will now be standardized automagically in 4.1)
- rework structure for install question, to more easily add a "disclaimer" key
- simplify format of "maintainers"

The idea is also to provide a script that automatically convert existing manifests to the new format for easier transition (and also to avoid having legacy mess all over the place in the core)

(Feel free to share thoughts etc)

Here's what it would look like in JSON with Wekan as example : 

```json
{
    "name": "Wekan",
    "id": "wekan",
    "packaging_format": 2,

    "description": {
        "en": "Trello-like kanban",
        "fr": "Un kanban similaire à Trello"
    },

    "upstream": {
        "license": "MIT",
        "site": "https://wekan.io",
        "demo": null,
        "code": "https://github.com/wekan/wekan",
        "doc": "https://github.com/wekan/wekan/wiki"
    },

    "package": {
        "version": "4.09~ynh1",
        "maintainers": {
             "alexAubin": "alex.aubin@mailoo.org",
             "ljf": "???"
        },    
        "requirements": {
            "yunohost": ">= 3.8",
            "architecture": ["amd64"],
            "memory": "500M"
        },
        "integration": {
            "ldap": true,
            "sso": false,
            "multi_instance": "notrelevant",
            "fail2ban": false
        }
    },

    "install": {
        "disclaimer": {
            "en": "Here we can tell something to the admin before the installation",
            "fr": "Ici on peut dire des trucs à l'admin avant l'install"
        },
        "questions": [
            {
                "name": "domain",
                "type": "domain"
            },
            {
                "name": "path",
                "type": "path",
                "default": "/wekan"
            },
            {
                "name": "admin",
                "type": "user"
            },
            {
                "name": "is_public",
                "type": "boolean",
                "default": false,
                "help": {
                     "en": "In private mode, only authorized YunoHost members can access to the Wekan.",
                     "fr": "En mode privé, seul les membres Yunohost autorisés peuvent accéder au Wekan"
                }
            }
        ]
    }
}
```

and equivalent in TOML : 

```toml
name = "Wekan"
id = "wekan"
packaging_format = 2.0

[description]
en = "Trello-like kanban"
fr = "Un kanban similaire à Trello"

[upstream]
license = "MIT"
site = "https://wekan.io"
code = "https://github.com/wekan/wekan"
doc = "https://github.com/wekan/wekan/wiki"

[package]
version = "4.09~ynh1"

  [package.maintainers]
  alexAubin = "alex.aubin@mailoo.org"
  ljf = "???"

  [package.requirements]
  yunohost = ">= 3.8"
  architecture = [
    "amd64"
  ]
  memory = "500M"

  [package.integration]
  ldap = true
  sso = false
  multi_instance = "notrelevant"
  fail2ban = false

[install]

  [install.disclaimer]
  en = "Here we can tell something to the admin before the installation"
  fr = "Ici on peut dire des trucs à l'admin avant l'install"

  [[install.questions]]
  name = "domain"
  type = "domain"

  [[install.questions]]
  name = "path"
  type = "path"
  default = "/wekan"

  [[install.questions]]
  name = "admin"
  type = "user"

  [[install.questions]]
  name = "is_public"
  type = "boolean"
  default = false

    [install.questions.help]
    en = "In private mode, only authorized YunoHost members can access to the Wekan."
    fr = "En mode privé, seul les membres Yunohost autorisés peuvent accéder au Wekan"
```

**Comment by Krakinou** [comment]
My 2 cents : A mechanism that allow to ask new question during an upgrade.
For example when new option became available in the upstream app or a new version of the package allows some new stuff, we may need to ask the admin some questions

**Comment by Axolotle** [comment]
I've been analyzing what was in arguments install and here's a dump in case it can be useful.  
Sorry it is in yaml for comments.

## install/action/config-panel arg keys
```yaml
# Label/question as single english string
ask: string
# Label/question as dict with locale as key
ask:
  en: string
  fr: string

# id
name: string

# field type
type: string # One from the types below

# an example
example: string

# default value
default: number|string|boolean

# Help message as single english string (every app that has help message use dict)
help: string
# Help message as dict with locale as key
help:
  en: string
  fr: string

# list of choices
choices: list<string|number|boolean>
# dict of choices (with key as value and value as label) (only one app, vue-bootstrap depreciated)
choices:
    value1: string
    value2: string
```

## Field types
```yaml
# Add a disclaimer (live example below from the only app using this type: flarum)
type: "diplay_text"

# Select a domain (with admin's domains as choices)
type: "domain"

# Select a user (with admin's user list as choices)
type: "user"

# Input classic
type: "string"

# Path (input classic so could be removed, also can be kept so we can check if a domain is also asked to combo as an grouped select input)
type: "path"

# Checkbox
type: "boolean"

# Password (input type password)
type: "password"

# Number (input type number)
type: "number"

# Email (input type email)
type: "email"

# if undefined => input classic "string"
# if undefined && choices => select classic
```


Also, and from the web-admin point of vue (no clue for cli) some types could be useful or syntax could be different.
```yaml
# language select
type: "lang"
choices: ['ca', 'ar']
# as an array of locales that would be translated to a real language name if in web-admin locale list (i've added readable languages names for the locale chooser in the web-admin)

# choices syntax rewrite (optionnal, can still be an array of strings)
choices:
    - { value: number|string, text: string|dict } # text can be a dict with locale as key (same as ask and help)
    - ...

# email (input type email selector == input combine with a select with yunohost user emails ? etc.))
# there is actually an app using this type => django_app
type: email
```

Example of the `display_text` arg (currently only one item is extract from the install args and displayed first)
![image](https://user-images.githubusercontent.com/5127669/96249287-4406fe80-0fad-11eb-9450-9f793324fb4b.png)

**Comment by alexAubin** [comment]
New iteration on this, gonna try to implement this during the yunocamp, to be discussed:

```toml
packaging_format = 2

id = "wordpress"
name = "WordPress"
description.en = "Create a beautiful blog or website easily"
description.fr = "Logiciel de création de blog ou de site Web"

version = "5.8~ynh1"

[upstream]
license = "GPL-2.0"
website = "https://wordpress.org/"
admindoc = "https://codex.wordpress.org/"
userdoc = "https://yunohost.org/#/app_wordpress"
code = "https://core.trac.wordpress.org/browser  "

[integration]
yunohost = ">= 4.1.2"
architectures = "all" # Can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature, for example: ["amd64", "i386"]
multi_instance = true
ldap = "?"
sso = "?"

[install]
    [install.domain]
    # # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/blog"

    [install.admin]
    # # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.language]
    ask.en = "Choose the language of the WordPress site"
    ask.fr = "Choissisez la langue du WordPress"
    type = "string"
    choices = ["en_US", "fr_FR"]
    default = "en_US"

    [install.multisite]
    ask.en = "Enable multisite option?"
    ask.fr = "Activer l'option multisite ?"
    type = "boolean"
    default = false

    [install.is_public]
    # # this is a generic question - ask strings are automatically handled by Yunohost's core
    help.en = "A public WordPress will be publicly visible for everyone. If you're looking for a public blog, you should choose to install a public WordPress."
    help.fr = "Un WordPress public sera visible publiquement pour tous. Si vous recherchez un blog public, vous devriez choisir d'installer un WordPress public."
    type = "boolean"
    default = true

[resources]
    [resources.disk]
    build = "50M" # This is an *estimate* minimum value for the disk needed at build time (e.g. during install/upgrade) and during regular usage
    usage = "50M" # Please only use round values such as: 10M, 100M, 200M, 400M, 800M, 1G, 2G, 4G, 8G

    [resources.ram]
    build = "50M" # This is an *estimate* minimum value for the ram needed at build time (e.g. during install/upgrade) and during regular usage
    usage = "10M" # Please only use round values such as: 10M, 100M, 200M, 400M, 800M, 1G, 2G, 4G, 8G
    include_swap = false

    [resources.route]
    url = "{domain}{path}"

    [resources.install_dir]
    base_dir = "/var/www/" # This means that the app shall be installed in /var/www/$app which is the standard for webapps. You may change this to /opt/ if the app is a system app.
    alias = "final_path"
```
