### ISSUE TITLE
Restricting  mail-forward and email-alias for particular users/group

### ISSUE THREAD

**Issue by anmol26s** [YunoHost/issues#1675]
As requested on the Forum. https://forum.yunohost.org/t/prevent-users-from-adding-e-mail-addresses/13169

Email alias and forwarding should only be allowed to users or groups which are allowed by admin. Giving this feature to non trusted users(Maybe for testing or Demo for users) will be dangerous. ++ This feature is the only down side which restrict Yunohost to be used as an small company. Manager will not want every user in his team to be able to send email from manager@doman.tld or info@domain.tld.

**Comment by anmol26s** [comment]
The work flow which @alexAubin  suggested is to add permission for each property(mailalias and email forwarding) in LDAP just like we have XMPP and E-mail permission right now. This would allow admin to add or remove these properties for each user and group. Then checks can be implemented from SSO and REST API to display these option in SSO edit page for the users granted these permissions.

So, I have tried appended following lines to  _ldap_scheme.yml_ to have two new permissions.

```
cn=mailalias.main,ou=permission:
    cn: mailalias.main
    gidNumber: "5003"
    objectClass:
      - posixGroup
      - permissionYnh
    groupPermission:
      - "cn=all_users,ou=groups,dc=yunohost,dc=org"
    authHeader: "FALSE"
    label: "Mail-alias"
    showTile: "FALSE"
    isProtected: "TRUE"
  cn=mailforward.main,ou=permission:
    cn: mailforward.main
    gidNumber: "5004"
    objectClass:
      - posixGroup
      - permissionYnh
    groupPermission:
      - "cn=all_users,ou=groups,dc=yunohost,dc=org"
    authHeader: "FALSE"
    label: "Mail-forward"
    showTile: "FALSE"
    isProtected: "TRUE"
```

But these new permission are not shown in permission list. If someone has an idea how these permission work or get generated, it would be helpful.
