### ISSUE TITLE
Allow users to self-register (or with invitation link)

### ISSUE THREAD

**Issue by zamentur** [YunoHost/issues#1677]
# User registration

We need a system to allow people to register on a yunohost instance. It's needed for our small community server roadmap.

### 3 registration modes
Invitation-link-only : The registration form is not publicly displayed in SSO. The admin can generate an invitation link and send it to the future user
Admin-validation : The registration form is publicly displayed in SSO, but the user should be validated by admin manually
Public : The registration form is publicly displayed in SSO, and user can access directly to the new created account (after email validation ?).

### Email validation
If the instance has a valid email stack. The admin could activate the email validation feature. To create an account you need to click on a validation link.
Email validation link expiration: 7 days ?

### CAPTCHA validation
We need to avoid robot and spam.

### Create settings
Add a settings "user.registration.mode" with choices "invitation-link-only", "admin-validation", "public" . See this line to add the settings: https://github.com/YunoHost/yunohost/blob/dev/src/yunohost/settings.py#L56

Add a settings "user.registration.email_validation" Boolean (linked to Password reset feature)

### Create API/CLI endpoints
Create API/CLI endpoints as a subcategories of `user` called `subscription` https://github.com/YunoHost/yunohost/blob/dev/data/actionsmap/yunohost.yml#L207 The associated code could be added in https://github.com/YunoHost/yunohost/blob/dev/src/yunohost/user.py#L498 . See group subcategories to find example how to write the code.

The data could be registered inside a YAML file in /etc/yunohost/subscriptions.yml

```
invitations:
  - code: 58TFr7566BB95Fg
    groups:
       - moderators
    quota: 10G
    nb_account: 10
    timestamp: 153152215441
  - code: C5HHbsfsdfg98
    groups:
       - moderators
    quota: 1G
    email: camille@gmail.com
    nb_account: 1
    timestamp: 153152215441
subscriptions:
  - login: john
    firstname: john
    lastname: doe
    email: john@example.com
    hash_pwd: $6$....
    email_rescue: john@gmail.com
    email_validation: validated
    groups:
       - moderators
    timestamp: 153152215441
  - login: jane
    firstname: jane
    lastname: doe
    email: jane@example.com
    hash_pwd: $6$....
    email_rescue: jane@gmail.com
    email_validation: PPo543ccxgdf9
    groups:
       - friends
    timestamp: 153152215441
```

#### Administrator actions

**List all current subscriptions**
yunohost user subscription list  |  GET /yunohost/api/user/subscriptions

    Return a list of all current waiting subscriptions/invitations with statuts like 'email validated: yes/no'

**Accept / refuse a subscription**
yunohost user subscription accept LOGIN  |  POST /yunohost/api/user/subscriptions/:login/accept
yunohost user subscription delete ID  |  DELETE /yunohost/api/user/subscriptions/:id

**Create an ephemereal invitation code/link**
yunohost user subscription invite [--groups GROUP1 ...] [-q {SIZE|0}] [--send-to EMAIL] |  POST /yunohost/api/user/subscriptions/invite

#### Future user actions
The user won't use this API endpoints directly. He/she will use SSO pages that will use those API endpoints.

Note those API could be separated from the ADMIN API. But if we do that it makes some works to create the API stuff. There is also the password reset feature with same issues.

**Register**
GET /yunohost/api/user/subscriptions/captcha
POST /yunohost/api/user/subscriptions 
public API endpoints with 'authenticate: false' like for `yunohost tools postinstall` or `yunohost backup restore` 

POST DATA:
USERNAME [--code INVITATION_CODE] [--groups GROUP1 ...] -f FIRSTNAME -l LASTNAME [-m MAIL] [-p PASSWORD] [-q {SIZE|0}?????]

**Email validation**
yunohost user subscription resend LOGIN  |  POST /yunohost/api/user/subscriptions/:login/resend
yunohost user subscription validate  |  POST /yunohost/api/user/subscriptions/:login/accept 
POST /yunohost/api/user/subscriptions/:id/validate/:validation_code

+ cron to clean old validation/invitation links

#### Change app_ssowatconf
Change app_ssowatconf to add user.registration.mode and user.registration.email_validation value in /etc/ssowat/conf.json  https://github.com/YunoHost/yunohost/blob/dev/src/yunohost/app.py#L1345

#### Add register link
Adapt SSO login view to display registration URL or not based on `registration mode` value
https://github.com/YunoHost/SSOwat/blob/dev/portal/login.html
https://github.com/YunoHost/SSOwat/blob/6a7a9d668e5a23ad5d1c0a1630c7b2c2b82ef19c/helpers.lua#L530

#### Add a registration form page
Add a registration form page in SSO that use Ajax query to call API
/yunohost/sso/registration/
-> POST /yunohost/api/user/subscriptions

/yunohost/sso/registration/?groups=XXXX
Registration page for a specific group ?

/yunohost/sso/registration/?invitation_code=XXXXXX
-> POST /yunohost/api/user/subscriptions?invitation_code=XXXXXX

/yunohost/sso/registration/?validation_code=XXXXXX
-> POST /yunohost/api/user/subscriptions/validate?validation_code=XXXXXX
