### ISSUE TITLE
Thoughts on new modern format for check_process

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1684]
So hmpf I'm a big fan of writing draft and got fed up of seeing the super-custom-homemade syntax of check_process files so decided to procrastinate sleeping and wrote a draft.

For simple / usual apps this could be as simple as : 

```toml
notify = "always"
notify_emails = ["foo@bar.com"]

# With tests = "auto", the relevant tests are guessed from the args in manifest
# (c.f. presence of domain/path, is_public, multi_instance, ...)
tests = "auto"

########################################
# Default args to use for installation #
########################################
# By default, the CI will fill the "usual" args like domain, path, admin, 
# is_public and password with relevant values automatically
# Here, only specify values of "non-standard" args with no default value in the manifest

[args]
multisite=0
language="fr_FR"

###########################################################################
# References for upgrade tests (in addition to upgrade from same version) #
###########################################################################

[[upgrade_ref]]
name="v3.79"
commit="2843d504bcdb0402939f87ebeeda3417de02a9e4"

[[upgrade_ref]]
name="v4.09"
commit="46f4b540cb99090a3fe1d35828094dbbfb34b692"
```

---
---

And then for more advanced apps with multiple "test suites" etc ... it could look like : 

---
---

```toml
notify = "always"
notify_emails = ["foo@bar.com"]

# With tests = "auto", the relevant tests are guessed from the args in manifest
# (c.f. presence of domain/path, is_public, multi_instance, ...)
# Though we may ban/ignore some tests if they are not relevant yet or for optimizations
tests = "auto"
tests_ignore = ["setup_private", "multi_instance", "actions"] 

# Some apps require to preinstall some stuff prior to each tests
preinstall = [
    "sudo yunohost domain add foobar.com",
    "sudo yunohost app install some_app -a 'domain=foobar.com'"
]

########################################
# Default args to use for installation #
########################################
# By default, the CI will fill the "usual" args like domain, path, admin, 
# is_public and password with relevant values automatically
# Here, only specify values of "non-standard" args with no default value in the manifest

[args]
multisite=0
language="fr_FR"

###########################################################################
# References for upgrade tests (in addition to upgrade from same version) #
###########################################################################

[[upgrade_ref]]
commit="00a1a6e7dd5c814f5084c11c2810f886a32bdf61"
name="Upgrade 5.4"
args="domain=DOMAIN&path=PATH&admin=USER&language=fr_FR&multisite=0&is_public=1&"

[[upgrade_ref]]
commit="0123456789abcdef0123456789abcdef01234567"

############################################
#  Config panel (and similar for actions)  #
############################################
# By default, the CI should guess what/how to 
# test in the config panel from the type or 
# available choices but it should be possible
# to specify custom values to test

[config_panel]
footprint=["low", "medium", "high"]
force_max_children=[0, 20] 
    
 ################################################
 #  Additional test with arguments variations   #
 ################################################
 
[[additional_test]]
     
     # Here, this test suite shall be limited to only a few tests
     tests = ["setup_sub_dir", "setup_private", "upgrade", "backup_restore"]
     
     [[additional_test.args]]
     multisite = 1
 
[[additional_test]]
     
     tests = ["setup_sub_dir"]

     [[additional_test.args]]
     language = "en_EN"
     
```

**Comment by alexAubin** [comment]
Got triggered today so I decided to give this a go

Wrote a magic script to parse and convert check_process to a new `tests.toml` : https://gist.github.com/alexAubin/637a6208cf14c8d3c02e4d24a4c0e06f

Changed a couple stuff from the original idea

Also this doesn't migrate specific stuff like actions/config panel because hmpf these will soon break again after the 4.3 gets released

Here's an example of auto-generated output when ran on wordpress's check_process:

```toml
[[test_suite]]
    description = "Default test suite"

    # With tests = "auto", the relevant tests are guessed from the args in manifest
    # (depending on the presence of domain/path, is_public, multi_instance, ...)
    tests = "auto"

    # You can also decide (though this is discouraged!) to ban/ignore some tests 
    # for example if they are not relevant yet, or for optimizations
    # tests = ["!install_private", "!install_multi"]   # <-- Run all relevant tests, except install_private and install_multi
    # tests = ["install_root"]  # <-- Run only install_root

    ########################################
    # Default args to use for installation #
    ########################################
    # By default, the CI will automagically fill the 'standard' args 
    # like domain, path, admin, is_public and password with relevant values.
    # Here, you can specify values for 'non-standard' args *with no default value defined in the manifest*

    args.language = "fr_FR"
    args.multisite = 0

    [[test_suite.upgrade_ref]]
    commit = "00a1a6e7dd5c814f5084c11c2810f886a32bdf61"
    name = "Upgrade 5.4"
    args = "domain=DOMAIN&path=PATH&admin=USER&language=fr_FR&multisite=0&is_public=1&"


[[test_suite]]
    description = "Test avec multisite"

    tests = ["install_subdir"]
    args.language = "fr_FR"
    args.multisite = 1
```

**Comment by alexAubin** [comment]
Ooooor another design iteration (though no autoconvert yet, didn't even check if this is valid toml) :

```toml
[test_suite.main]
    description = "Default test suite"

    # The relevant tests to run are guessed from the manifest infos
    # You can also decide (though this is discouraged!) to ban/ignore some tests,
    # or run only some specific tests (VERY discouraged)
    # test_exclude = ["install_private", "install_multi"]
    # test_only = ["install_root"]

    ########################################
    # Default args to use for installation #
    ########################################
    # By default, the CI will automagically fill the 'standard' args 
    # like domain, path, admin, is_public and password with relevant values.
    # Here, you can specify values for 'non-standard' args *with no default value defined in the manifest*

    args.language = "fr_FR"
    args.multisite = 0

    test_upgrade_from.00a1a6e7.name = "Upgrade from 5.4"
    # By default, same args will be used as current install, but you may specify custom args with
    # test_upgrade_from.00a1a6e7.args.foo = "bar"


[test_suite.multisite]
    description = "Test avec multisite"

    test_only = ["install_subdir"]
    args.language = "fr_FR"
    args.multisite = 1
```
