### ISSUE TITLE
yunohost app remove only allows one app id at a time, despite its help suggesting the contrary

### ISSUE THREAD

**Issue by nils-van-zuijlen** [YunoHost/issues#1787]
`yunohost app remove` help is as follows, it suggests that it could take more than one app as argument, but in fact it can't.

```
usage: yunohost app remove app [-h]

Remove app

positional arguments:
  app         App(s) to delete

optional arguments:
  -h, --help  show this help message and exit
```

The versions I run:
```
yunohost: 
  repo: testing
  version: 4.1.7.2
yunohost-admin: 
  repo: stable
  version: 4.1.4
moulinette: 
  repo: stable
  version: 4.1.4
ssowat: 
  repo: stable
  version: 4.1.3
```
