### ISSUE TITLE
'yunohost diagnosis run' returns 0 even if it didn't run because of issues

### ISSUE THREAD

**Issue by nils-van-zuijlen** [YunoHost/issues#1790]
## What happens

I run `yunohost diagnosis run dnsrecords web --force` and the returncode is 0 with the following output in stderr:
```
Can't run diagnosis for DNS records while there are important issues related to Internet connectivity.
Can't run diagnosis for Web while there are important issues related to Internet connectivity.
```

## What I expected

I expected a non-zero output code, as 0 usually means all went well, and there has been an error.

## My versions

```
yunohost: 
  repo: stable
  version: 4.1.8
yunohost-admin: 
  repo: stable
  version: 4.1.4
moulinette: 
  repo: stable
  version: 4.1.4
ssowat: 
  repo: stable
  version: 4.1.3
```
