### ISSUE TITLE
New password not accepted

### ISSUE THREAD

**Issue by lejocelyn** [YunoHost/issues#1825]
Hi,

Both using this interface:
https://serveur.jocelynaznar.eu/yunohost/sso/edit.html
or this one:
https://serveur.jocelynaznar.eu/yunohost/admin/#/users/lejocelyn/edit

I tried multiple times to change my password though Yunohost web interface, and it seems that the new password was accepted. But in the end, the password is not updated and I still have to use the old password.

I installed yunohost through the official yunohost iso.

**Comment by zamentur** [comment]
This password contains specific chars ?

**Comment by lejocelyn** [comment]
No, it's a password generated by Firefox. It works now actually, I needed to restart the server for it to be accepted.

**Comment by shukon** [comment]
I experience this also.

```
yunohost: 
  repo: stable
  version: 4.2.6.1
yunohost-admin: 
  repo: stable
  version: 4.2.3.3
moulinette: 
  repo: stable
  version: 4.2.3.3
ssowat: 
  repo: stable
  version: 4.2.3
```

The only way to change the password is using CLI. I cannot try the restart option at the moment, but it would not be desirable to restart the server after any of the users change their password anyway...

I found [this](https://forum.yunohost.org/t/cant-change-users-password-after-upgrade/16292) but fail to understand the french part.

Anything I can do to help debug this?
