### ISSUE TITLE
Can’t login into admin interface after update to 4.3.2

### ISSUE THREAD

**Issue by xplosionmind** [YunoHost/issues#1918]
### Describe the bug

I cannot log into the admin interface after having updated my server to 4.3

### Context

- Hardware: *VPS bought online*
- YunoHost version: 4.3.2.2
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - If yes, please explain: *Just updated to 4.2.8 to 4.3.2.2*

### Steps to reproduce

- clicking “upgrade” from the webadmin
- closing everything
- trying to log back in:
   - It works for the user interface
   - it does not work for the webadmin interface
- rebooting the server and refreshing the browser
- same result

### Expected behavior

Logging in normally

### Logs

`yunohost log list`:
```
  47:
    description: Upgrade the 'nextcloud' app
    name: 20211104-111020-app_upgrade-nextcloud
    path: /var/log/yunohost/categories/operation/20211104-111020-app_upgrade-nextcloud.yml
    started_at: 2021-11-04 12:10:20
  48:
    description: Upgrade system packages
    name: 20211107-095220-tools_upgrade
    path: /var/log/yunohost/categories/operation/20211107-095220-tools_upgrade.yml
    started_at: 2021-11-07 10:52:20
  49:
    description: Regenerate system configurations 'all'
    name: 20211107-095312-regen_conf-all
    path: /var/log/yunohost/categories/operation/20211107-095312-regen_conf-all.yml
    started_at: 2021-11-07 10:53:12
```

- `sudo yunohost log show 20211107-095220-tools_upgrade --share`: [output here](https://paste.yunohost.org/raw/nogusayudu'
- `sudo yunohost log show 20211107-095312-regen_conf-all --share`: [output here](https://paste.yunohost.org/raw/yowofiloqu)

<img width="1440" alt="Screenshot 2021-11-07 at 11 23 40 AM" src="https://user-images.githubusercontent.com/42862428/140641736-2a61f2f0-d5ec-4f49-9017-cc7e8fccac7e.png">
