### ISSUE TITLE
Thoughts on a more modern way to declare app sources

### ISSUE THREAD

**Issue by alexAubin** [YunoHost/issues#1978]
### Problem

- Having to create and update dozens of `conf/foo.src` is cumbersome - especially for apps with many sources pieces - or when they are arch-dependents.
- Many options in the current `app.src` syntax are either unecessary (because the default is fine) or obscure (pretty sure `SOURCE_FILENAME` isnt actually used by anybody). All of this could be simplified.

### Proposal

- Have a single `sources.toml` at the root of the package (like `manifest.toml`) which would list all upstream sources. Listing everything in a single file is more handy because it implies less switching between dozens of file when having to update them.

- Use sha256sum everywhere as the standard for sum. I doubt there's any advantage to use super-specific checksums elsewhere.

- **Simplest case** : app with a single source in a tar.gz. Call to `ynh_setup_source` will use the `app` id by default

```toml
[app]
url = "https://foobar.com/some/path/to/archive.tar.gz"
sha256 = "a1071ab783f4d47553ac38a5357b7ce801c8cfe3e523280feead865e23b7da2e"
```

- Other dependencies / modules / pieces / ... may be added with another name, in the same file. `ynh_setup_source` should be called with `--source_id=derpyderp` to use it.

```toml
[derpydep]
url = "https://foobar.com/some/path/to/derpydep.tar.gz"
sha256 = "583898eb907c21dbbcb6f33934eae3dc1d6ec2620fdc7689c70a3479049af52b"
```

- Source depending on arch. In that case `ynh_setup_source` will automatically pick the url/sha256 corresponding to `$YNH_ARCH` / `dpkg --print-architecture`

```toml
[app]
url.amd64 = "https://foobar.com/some/path/to/archive-amd64.tar.gz"
sha256.amd64 = "a1071ab783f4d47553ac38a5357b7ce801c8cfe3e523280feead865e23b7da2e"
url.i386 = "https://foobar.com/some/path/to/archive-i386.tar.gz"
sha256.i386 = "5357b7ce801c8cfe3e523280feead865e23b7da2ea1071ab783f4d47553ac38a"
url.arm64 = "https://foobar.com/some/path/to/archive-arm64.tar.gz"
sha256.arm64 = "cfe3e523280feec8b7da2ea1071ab783f4d47553ac38aad865e235357b7ce801"
url.armhf = "https://foobar.com/some/path/to/archive-armhf.tar.gz"
sha256.armhf = "eec8b7d23280faad8657ce801e235357ba2ea1071ab783f4d47553ac38cfe3e5"
```

- Advanced options : by default, `ynh_setup_source` should guess the format from the url (e.g. ending with `.tar.gz`, `.deb`, ...) and wether or not to extract the file. For other specific use cases, those options should be usable to define how `ynh_setup_source` should behave:

```toml
in_subdir = ....   # defaults to false, to be set to true or an integer for the number of subdir
extract = ...      # defaults to true for .tar.gz, false for .deb, (to be studied what other relevant format there is) ... or can be set explicitly otherwise
```

- Other ideas to investigate:
   - instead of having to define an URL per arch, the URL could contain `__ARCH__` if the upstream uses the appropriate nomenclature ... one would still need to provide sha256 for all archs though.
   - instead of having to update the version number all the time, the URL could contain `__VERSION__` ... one would still need to update the sha256 though.
