### ISSUE TITLE
Generalize config panels into the core and helpers (such as php-fpm perf tweaks)

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#2045]
_(discussed with @zamentur and @alexAubin during YunoCamp 2022)_

### Reasons

Right now we use a generic copy-and-pasted set of config panel instructions to handle PHP configuration:

`config_panel.toml`:
```toml
[main]
name = "<app> configuration"

    [main.php_fpm_config]
    name = "PHP-FPM configuration"

        [main.php_fpm_config.fpm_footprint]
        ask = "Memory footprint of the service?"
        choices = ["low", "medium", "high", "specific"]
        default = "low"
        help = "low <= 20Mb per pool. medium between 20Mb and 40Mb per pool. high > 40Mb per pool.<br>Use specific to set a value with the following option."

        [main.php_fpm_config.free_footprint]
        ask = "Memory footprint of the service?"
        type = "number"
        default = "0"
        help = "Free field to specify exactly the footprint in Mb if you don't want to use one of the three previous values."

        [main.php_fpm_config.fpm_usage]
        ask = "Expected usage of the service?"
        choices = ["low", "medium", "high"]
        default = "low"
        help = "low: Personal usage, behind the SSO. No RAM footprint when not used, but the impact on the processor can be high if many users are using the service.<br>medium: Low usage, few people or/and publicly accessible. Low RAM footprint, medium processor footprint when used.<br>high: High usage, frequently visited website. High RAM footprint, but lower on processor usage and quickly responding."
```

`scripts/config`:
```bash
#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

phpversion=$(ynh_app_setting_get --app=$app --key=phpversion)
current_fpm_footprint=$(ynh_app_setting_get --app=$app --key=fpm_footprint)

#=================================================
# SPECIFIC GETTERS FOR TOML SHORT KEY
#=================================================

get__fpm_footprint() {
    # Free footprint value for php-fpm
    # Check if current_fpm_footprint is an integer
    if [ "$current_fpm_footprint" -eq "$current_fpm_footprint" ] 2> /dev/null
    then
        echo "specific"
    else
        echo "$current_fpm_footprint"
    fi
}

get__free_footprint() {
    # Free footprint value for php-fpm
    # Check if current_fpm_footprint is an integer
    if [ "$current_fpm_footprint" -eq "$current_fpm_footprint" ] 2> /dev/null
    then
        # If current_fpm_footprint is an integer, that's a numeric value for the footprint
        echo "$current_fpm_footprint"
    else
        echo "0"
    fi
}

#=================================================
# SPECIFIC SETTERS FOR TOML SHORT KEYS
#=================================================

set__fpm_footprint() {
    if [ "$fpm_footprint" != "specific" ]
    then
        ynh_app_setting_set --app=$app --key=fpm_footprint --value="$fpm_footprint"
    fi
}

set__free_footprint() {
    if [ "$fpm_footprint" = "specific" ]
    then
        ynh_app_setting_set --app=$app --key=fpm_footprint --value="$free_footprint"
    fi
}

#=================================================
# GENERIC FINALIZATION
#=================================================

ynh_app_config_validate() {
    _ynh_app_config_validate

    if [ "${changed[fpm_usage]}" == "true" ] || [ "${changed[fpm_footprint]}" == "true" ] || [ "${changed[free_footprint]}" == "true" ]; then
        # If fpm_footprint is set to 'specific', use $free_footprint value.
        if [ "$fpm_footprint" = "specific" ]
        then
            fpm_footprint=$free_footprint
        fi

        if [ "$fpm_footprint" == "0" ]
        then
            ynh_print_err --message="When selecting 'specific', you have to set a footprint value into the field below."

            exit 0
        fi
    fi
}

ynh_app_config_apply() {
    _ynh_app_config_apply

    ynh_add_fpm_config --phpversion=$phpversion --usage=$fpm_usage --footprint=$fpm_footprint
}

ynh_app_config_run $1

```

Their relevance and easiness-to-understand are debatable, but most importantly, they will be most likely the same for many apps.

### Solution

Let's factorize them:

- the bash code can be called through a helper
- the YunoHost core could override the config panel so that `[php]` config panels are automatically prepended with the `php_fpm_config` section shown above.
