### ISSUE TITLE
Add OpenID Connect support using Dex

### ISSUE THREAD

**Issue by navanchauhan** [YunoHost/issues#2051]
A lot of apps do not support using LDAP for authentication, but a lot of newer apps do support login via OpenID Connect. I propose we add a helper / support for [Dex](https://github.com/dexidp/dex) a service that can tap into YunoHost's LDAP using a connector and provide these apps with the correct tokens.

## Example
Outline is a software that requires social login (Slack/Google/ any other OIDC login), this [package](https://github.com/YunoHost-Apps/outline_ynh) by Limezy downloads the [Dex package](https://github.com/YunoHost-Apps/dex_ynh) and integrates it with outline so users can use their YunoHost credentials to login to the app.

## Proposal

I propose the following features:
* Dex helper which can create a new OpenID connect adapter for the apps 
* Reserving a part of the url for installing the Dex app (`/yunohost/dex/__APP__`)

**Comment by navanchauhan** [comment]
Example config: https://github.com/dexidp/dex/blob/master/examples/config-dev.yaml

We can either have multiple instances of Dex and bind each app to a dev instance using the configuration file, or someone will have to figure out the gRPC API that Dex exposes: https://dexidp.io/docs/api/

edit: I was wrong. We would only need one instance as you can have multiple clients

```
staticClients:
- id: example-app
  redirectURIs:
  - 'http://127.0.0.1:5555/callback'
  name: 'Example App'
  secret: ZXhhbXBsZS1hcHAtc2VjcmV0
#  - id: example-device-client
#    redirectURIs:
#      - /device/callback
#    name: 'Static Client for Device Flow'
#    public: true
```
