### ISSUE TITLE
Domains created/deleted through the CLI are not listed/unlisted in the webadmin

### ISSUE THREAD

**Issue by tituspijean** [YunoHost/issues#2068]
### Describe the bug

Domains created or deleted through the CLI are not appearing in or disappearing from the webadmin unless:
- another domain is altered through the webadmin
- the YunoHost API service is restarted

### Context

- Hardware: any?
```
yunohost -v
yunohost:
  repo: stable
  version: 11.0.9.12
yunohost-admin:
  repo: stable
  version: 11.0.10
moulinette:
  repo: stable
  version: 11.0.9
ssowat:
  repo: stable
  version: 11.0.9
```
- I have access to my server: SSH and webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no

### To reproduce

1. Create domain through the CLI: `yunohost domain add test.tld`
2. Refresh webadmin: the domain is not listed
3. `yunohot domain list`: the domain is listed
4. Either restart the API service or create a domain with the webadmin
5. The test domain appears

### Expected behavior

Domain API list should be updated when using CLI

### Logs

`yunohost domain add... ` : https://paste.yunohost.org/raw/vamizoyaho (sorry, plenty of domains in that server...)
