### ISSUE TITLE
ssowat 11.0.11 breaks nexcloud client connection (desktop or android client)

### ISSUE THREAD

**Issue by Br1x** [YunoHost/issues#2129]
### Describe the bug

Since the upgrade to ssowat=11.0.11 the nextcloud client (desktop or android) is unable to log in to nextcloud serveur : client get http 401
 
### Context

- Hardware: *VPS bought online*
- YunoHost version: 11.1.0.2
```
yunohost: 
  repo: testing
  version: 11.1.0.2
yunohost-admin: 
  repo: testing
  version: 11.1.0.2
moulinette: 
  repo: stable
  version: 11.0.9
ssowat: 
  repo: stable
  version: 11.0.11
```
- I have access to my server: *Through SSH, webadmin*
- Since the upgrade from ssowat=11.0.9 to ssowat=11.0.11 two days ago, all clients fail to log in to nexcloud. Users can use nextcloud webUI to work but can't sync files anymore with nextcloud desktop client.

### To reproduce

As i am not able to downgrade from ssowat=11.0.11 to ssowat=11.0.9, i can't reproduce the issue. ssowat=11.0.9 seems not to be available on the repo (`apt install ssowat=11.0.9` failed). 

Idealy, 

- get a ynh installation with a ssowat=11.0.9 and the nextcloud app.
- connect a nextcloud desktop client to the nextcloud app for sync files
- upgrade the ssowat to 11.0.11

### Expected behavior

Nextcloud desktop client should be capable to log in the nextcloud app as previously

#### /var/log/nginx/mydomain.tld-access.log

```
aa.bb.cc.dd - - [13/Jan/2023:14:02:14 +0100] "GET /nextcloud/status.php HTTP/1.1" 401 456 "-" "Mozilla/5.0 (Linux) mirall/3.4.2-1ubuntu1 (Nextcloud, ubuntu-5.15.0-58-generic ClientArchitecture: x86_64 OsArchitecture: x86_64)"
```

#### /var/log/nginx/mydomain.tld-error.log

```
2023/01/13 14:02:14 [error] 35593#35593: *8234 [lua] helpers.lua:385: authenticate(): Connection failed for: jenny, client: aa.bb.cc.dd, server: mydomain.tld, request: "GET /nextcloud/status.php HTTP/1.1", host: "mydomain.tld"
```
