### ISSUE TITLE
yunohost-admin page is blank

### ISSUE THREAD

**Issue by PatBriPerso** [YunoHost/issues#2257]
### Describe the bug

My YunoHost Admin page is blank.
Errors are displayed in my browser (see below).

### Context

- Hardware: *VPS bought online*
- YunoHost version: *11.2.4*
- yunohost-admin version: *11.2.2*
- I have access to my server: *Through SSH*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *no*

### To reproduce

I think I have this problem since I upgrade my YunoHost instance from 11.2.3 to 11.2.4 for YunoHost and 11.2.1 to 11.2.2 for YunoHost Admin. I make both updates in once from the Admin UI (and probably update some others system packages).

### Expected behavior

YunoHost Web Admin page should be displayed.

### Logs

There was no error displayed during my upgrade (or at the end).
And I was not able to find the log file for my system update : I watch in `/var/log/yunohost/categories/operation/` and I do not see it. Is the log for a system upgrade put somewhere else?

The `sudo yunohost --version` says:
```yaml
yunohost: 
  repo: stable
  version: 11.2.4
yunohost-admin: 
  repo: stable
  version: 11.2.2
moulinette: 
  repo: stable
  version: 11.2
ssowat: 
  repo: stable
  version: 11.2
```

The errors I see in my browser:
![image](https://github.com/YunoHost/issues/assets/5013009/3e6ad105-7026-4ba7-9ce4-527a565926b7)

When I look at the files in `/usr/share/yunohost/admin/assets/`, I do not find those 2 files...

I see now that all the files in this directory are timestamped on 2023-08-31. May be, the yunohost-admin "app" has not been installed :thinking:
