### ISSUE TITLE
Config panel - type `tags` not respected when we set also choice `choices`

### ISSUE THREAD

**Issue by Josue-T** [YunoHost/issues#2374]
### Describe the bug

Following the documentation here https://yunohost.org/fr/dev/forms#tags we expect to have support for tags with choices values.

So following the documentation we can create this following entry into the config panel:
```toml
        [emailreports.weekly.emailreports_weekly_graphs]
        ask.en = "Weekly mail reports graphs list"
        type = "tags"
        choices = ["system", "kern", "proc", "fs", "du", "net", "netstat", "process", "serv", "mail", "port", "user", "nginx", "mysql", "pgsql", "fail2ban", "memcached", "redis", "phpfpm", "int"]
        help = "List of graph names you want to appear in the email report. The names are the same as their .rrd files. There is a list of them in the graph_name option in monitorix.conf."
```

#### Expected

We expect to have the possibility to select multiple of the provided value.

#### Currently

We have the same select field than if we set `type = "select"`

### Context

- YunoHost version: 11.2.11.2
- Tested with app monitorix. But the issue should happen with any app

### To reproduce

Install monitorix and see the config panel or create/edit an app and add the previous toml part into the config panel.

### Expected behavior

We expect to have the possibility to select multiple of the provided value.
