### ISSUE TITLE
Helpers resource

### ISSUE THREAD

**Issue by orhtej2** [YunoHost/issues#2389]
Add support for using additional, externally supplied helpers in application scripts:

```toml
[resources]
 [resources.helpers]
   core.version = 'current'   ## optional, this is the default value, always present at SOME version
   mongodb.version = 'v1.3'
```

This would magically source the following helpers (no need for `source /usr/share/yunohost/helpers`):
 - core helpers in the version shipped with currently installed release of YunoHost
 - mongodb helpers from `yunohost/mongodb` from tag `v1.3`

If this is omitted from `manifest.toml` a default of sourcing `core@current` is used.

This aims to remove copy-pasted experimental helpers for `mongodb`, `redis`, Matrix bridges etc.

We may even consider moving `core` helpers to separate repo to decouple YunoHost versioning from helpers versioning.
