### ISSUE TITLE
Bookworm: SSO/App packaging: Email not present in headers since Yunohost 12.x?

### ISSUE THREAD

**Issue by fflorent** [YunoHost/issues#2413]
### Describe the bug

As a packager, I use the passed email header to authenticate a user through the SSO.

In Yunohost 11.2.*, it seems the email header is passed. But not when using Yunohost in version 12:
```
yunohost: 
  repo: unstable
  version: 12.0.0+202406131230
yunohost-admin: 
  repo: unstable
  version: 12.0.0+202403262345
moulinette: 
  repo: unstable
  version: 12.0.0+202311271500
ssowat: 
  repo: unstable
  version: 12.0.0+202403291800
```
