### ISSUE TITLE
ynh-dev: version is not defined

### ISSUE THREAD

**Issue by fflorent** [YunoHost/issues#2464]
### Describe the bug

After having installed ynh-dev, and run the post-install, `yunohost --version` returns the following result:
```
yunohost: 
  repo: ?
  version: ?
yunohost-admin: 
  repo: ?
  version: ?
moulinette: 
  repo: ?
  version: ?
ssowat: 
  repo: ?
  version: ?
```

### To reproduce

``` bash
curl https://raw.githubusercontent.com/yunohost/ynh-dev/master/deploy.sh | bash
cd ynh-dev
./ynh-start
# now inside the incus container
yunohost tools postinstall
# Follow the steps
yunohost --version
```

### Expected behavior

You should get the relevant versions.
