### ISSUE TITLE
There's `OK` button on progress dialogs in WebAdmin that does nothing.

### ISSUE THREAD

**Issue by orhtej2** [YunoHost/issues#2520]
### Describe the bug

See screenshot below.
Entering 'System update' and (un)installing app now opens modal dialog with `OK` button visible that does nothing.
This used to not be the case 🤷 

```
yunohost:
  repo: stable
  version: 12.0.11
yunohost-admin:
  repo: stable
  version: 12.0.5
yunohost-portal:
  repo: stable
  version: 12.0.7
moulinette:
  repo: stable
  version: 12.0.4
ssowat:
  repo: stable
  version: 12.0.3
```

### Context

- Hardware: VPS bought online
- YunoHost version: See above
- I have access to my server: Through SSH/through the webadmin/direct access via keyboard / screen 
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
  - If yes, please explain: n/a
- Using, or trying to install package version/branch: n/a
- If upgrading, current YunoHost version: n/a

### To reproduce

In web admin, perform any operation that opens progress modal.

### Expected behavior

No OK button as this dialog shouldn't be dismissable.

### Logs

Screenshot:

![Image](https://github.com/user-attachments/assets/41e31306-6dbb-4bdd-96cf-2cd2b7afe730)
