### ISSUE TITLE
methods argument of "yunohost backup create" doesn't require value

### ISSUE THREAD

**Issue by olberger** [YunoHost/issues#2536]
### Describe the bug

`yunohost backup create --methods` doesn't require any value, and creates a backup anyway.

It should report an error about missing backup method, if none provided.

Same happens with non-existant backup method like `yunohost backup create --method customwhatevervalue`

In both cases, the backup is created : 
```
Info: Collecting files to be backed up for 
[...]
Info: Creating a backup archive from the collected files…
Info: The archive will contain about 3.2GB of data.
Success! Backup created: 20250214-134154
name: 20250214-134154
results: 
  apps: 
    [...]
  system: 
    conf_ldap: Success
    conf_manually_modified_files: Success
    conf_ynh_certs: Success
    conf_ynh_settings: Success
    data_home: Success
    data_mail: Success
    data_multimedia: Success
size: 3470742946
root@ynh:~# echo $?
0
```

### Context
```
yunohost: 
  repo: stable
  version: 12.0.11
yunohost-admin: 
  repo: stable
  version: 12.0.5
yunohost-portal: 
  repo: stable
  version: 12.0.7
moulinette: 
  repo: stable
  version: 12.0.4
ssowat: 
  repo: stable
  version: 12.0.3
```
