### ISSUE TITLE
12.1: SSE(?) : No logs during app upgrade

### ISSUE THREAD

**Issue by kay0u** [YunoHost/issues#2560]
### Describe the bug

Sometimes, in the testing version, when I click to upgrade an app, I can see the preupgrade backup process, but then I can't see the upgrade. Instead I get the message: "La connexion avec le serveur a été fermée pour des raisons inconnues. Peut-être que 'yunohost-api' ne répond plus ?". The upgrade is performed, but I don't see the logs in the "logs" section in the webadmin.

### Context

- Hardware: *x64*
- YunoHost version: 12.1.2 (**Testing**)
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - I run the testing version
- Using, or trying to install package version/branch:
- If upgrading, current YunoHost version:
```
yunohost: 
  repo: testing
  version: 12.1.2
yunohost-admin: 
  repo: testing
  version: 12.1.2
yunohost-portal: 
  repo: stable
  version: 12.0.8
moulinette: 
  repo: testing
  version: 12.1.0
ssowat: 
  repo: stable
  version: 12.0.3
```

### To reproduce

I'm not sure how to reproduce it everythime, but upgrade an app is the way to trigger this bug.

### Expected behavior

See the log after the pre-upgrade backup, the log is available in *Tools -> Logs* section

### Logs

<details>
  <summary>I dont have any</summary>
  
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣴⢿⣿⣷⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀ ⠀ ⠀ ⠀ ⠀ ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡿⣿⣭⢿⡧⢽⣿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⣵⡟⠉⣼⡇⣾⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣶⡿⡳⠛⠁⠀⠙⢺⣯⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢀⣀⣀⣀⣤⣤⣤⣤⣤⣠⣄⣠⣴⠟⠋⠀⠀⠀⢤⡾⠀⢘⢻⣧⣤⣠⣤⣴⣦⣶⣴⣤⣤⣤⣤⣄⣄⡀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⣰⡿⠿⣟⠙⠩⢍⡉⠉⠉⠉⠉⣹⠇⠀⠀⣴⡇⣠⣾⠇⠀⠈⠿⠟⠈⢦⣄⣀⣈⣉⣉⡉⢩⣬⣽⠿⠿⢷⣄⠀⠀⠀⠀
⠀⠀⠀⠀⣴⡿⠃⠀⠉⠋⠛⠛⠉⠀⠀⠀⠀⠛⢣⣤⡿⠋⠀⠘⠏⠐⠀⢀⠀⠀⠀⠀⠉⠛⠛⣛⣛⣿⣿⠋⠀⠀⠀⠀⠹⣧⡀⠀⠀
⠀⠀⠀⣼⡏⠀⠀⠀⠀⠀⠀⠀⠀⢦⣤⣤⣠⣴⡾⠁⢀⠀⠀⠀⠀⠀⠀⠈⠻⣶⣤⠀⠀⠀⠈⠉⣹⡟⠁⠀⠀⢀⠀⠀⠀⢺⣧⠀⠀
⠀⠀⢀⣾⠇⠀⠹⠻⡟⠃⠀⠀⠀⠀⣉⣩⣉⡉⡀⢀⠀⠀⡀⠀⢀⣀⣀⠀⠀⠀⠀⣀⢀⡀⡀⢀⣿⠁⠀⢦⡿⠛⠻⣷⡀⠀⣿⡄⠀
⠀⠀⣸⣿⣤⣤⣤⣴⣦⡄⠀⠀⠀⠘⠷⢷⠲⠛⠛⠛⠻⠛⡟⠻⠻⠛⠋⠀⠀⠀⠀⠻⠛⠟⢟⣻⡿⠀⢠⡿⠃⣠⠀⠸⣧⠈⣿⡀⠀
⠀⢐⢻⡏⠉⠉⠉⠉⠉⠁⠀⠀⠀⠀⠀⠈⠀⠀⣤⣄⡀⠀⡁⠀⠀⠀⠀⠀⡀⠀⠀⠀⠀⢀⠾⣿⡇⠐⣼⠇⣰⡿⣶⠠⣿⠀⣿⡅⠀
⠀⠀⣾⡇⠀⠈⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠛⠛⠻⠿⠿⠆⠀⠰⠟⠛⠛⠻⢛⠿⠋⢀⣿⡇⠠⣿⡄⢿⣄⣿⠀⣿⠐⣿⡆⠀
⠀⠀⣻⡷⠶⠷⢶⢦⠀⠀⠀⠈⠿⠿⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠻⣶⣶⣾⣿⣇⡘⢿⡅⠘⠿⠟⢸⡟⠀⣿⡇⠀
⠀⠀⢹⣷⡄⡀⠒⠀⡀⡀⠀⠀⣀⣀⣀⣀⠀⠀⠀⠠⣄⣠⣠⡄⠀⠀⠀⠀⢶⣦⣴⣤⢶⣦⣶⣿⣿⡀⠸⣷⡀⠀⠀⣿⠃⡀⣿⡇⠀
⠀⠀⠘⠹⣿⣅⠀⠀⠙⠛⠛⠛⠛⠛⠛⠋⠀⠀⠀⠀⠈⢭⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣷⠀⠈⣷⣀⣾⠋⠰⣰⡟⠄⠀
⠀⠀⠀⠀⠻⣷⣤⣀⡀⠀⠀⠀⠀⠀⠀⠠⣀⠀⠀⠀⠀⠈⠿⠷⠶⠶⠷⠷⢤⣤⣴⣤⣤⣤⣤⠌⠛⣿⡀⠀⠈⠉⠀⢀⣼⠏⠀⠀⠀
⠀⠀⠀⠀⠀⠈⢿⣭⣉⠛⠛⠛⠛⠁⢀⠀⠛⡿⠿⢷⢷⡷⣀⠀⢀⠀⠀⡀⠀⠀⠀⡙⣿⣿⢿⣿⣿⣿⣿⣄⣀⣠⣴⡿⠁⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠈⠉⠛⠛⠛⠛⠛⠛⠛⠛⠛⠳⠒⠶⠒⠷⠚⠶⠚⠖⠳⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠉⠁⠀⠀⠀⠀⠀⠀

</details>
