### ISSUE TITLE
12.1: SSE(?) No error displayed when we try to upgrade an app while a mandatory service is down

### ISSUE THREAD

**Issue by kay0u** [YunoHost/issues#2561]
### Describe the bug

In the testing version, for some reason my fail2ban service was down, I clicked to upgrade an app, the prebackup upgrade was done but the process stopped here without any error. To see the problem I had to open the browser console and saw that fail2ban was down.

### Context

- Hardware: *x64*
- YunoHost version: 12.1.2 (**Testing**)
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: *yes*
  - I run the testing version
- Using, or trying to install package version/branch:
- If upgrading, current YunoHost version:
```
yunohost: 
  repo: testing
  version: 12.1.2
yunohost-admin: 
  repo: testing
  version: 12.1.2
yunohost-portal: 
  repo: stable
  version: 12.0.8
moulinette: 
  repo: testing
  version: 12.1.0
ssowat: 
  repo: stable
  version: 12.0.3
```

### To reproduce

stop fail2ban service, try to upgrade an app.

### Expected behavior

We should get an error in logs, a popup or something else to warn admin that there is a mandatory service down.

### Logs

?
