### ISSUE TITLE
Doc for markdown config panel options provides example with display_text type

### ISSUE THREAD

**Issue by olberger** [YunoHost/issues#2588]
### Describe the bug

In the docs "Technical details for config panel structure and form option types", the markdown option type (https://doc.yunohost.org/en/contribute/dev/forms#markdown-readonly) provides an example where the type isn't set to `markdown`, but `display_text`, which is ambiguous:

```toml
[section.my_option_id]
type = "display_text"
ask = "Text **rendered** in markdown."
```

Source at: 
 https://github.com/YunoHost/doc/blob/6653aa63873d4c92366f198a06bd8901cafca4a5/pages/06.contribute/15.dev/03.forms/forms.md?plain=1#L237

I imagine that this may be for historical reasons. 

So either there should be a section on the "display_text" option type in the docs, or the example code should be fixed with `type = "markdown"`

Hope this makes sense.
