### ISSUE TITLE
yunohost app map do not list mumble app if installed

### ISSUE THREAD

**Issue by yunohost-bot** [YunoHost/issues#927]
###### Original Redmine Issue: [927](https://dev.yunohost.org/issues/927)

Author Name: **moul**

---

None

**Comment by Psycojoker** [comment]
@M5oul that looks suuuuper weird, are you sure the app was installed correctly?

**Comment by Jibec** [comment]
I do confirm the issue

```jb@jb9:~$ sudo yunohost app map
ff.jb9.fr/: Funkwhale
jb9.fr/baikal: Baikal
jb9.fr/date: OpenSondage
jb9.fr/ffsync: Firefox Sync Server
jb9.fr/kanboard/: Redirect
jb9.fr/kresus: Kresus
p.jb9.fr/: PeerTube
w.jb9.fr/pixelfed: Pixelfed
```

```
jb@jb9:~$ sudo yunohost app list --installed
apps: 
  0: 
    description: Serveur CalDAV+CardDAV léger
    id: baikal
    installed: True
    label: Baikal
    license: GPL-3.0
    name: Baikal
  1: 
    description: Le serveur de synchronisation de Mozilla, pour héberger vos données Firefox
    id: ffsync
    installed: True
    label: Firefox Sync Server
    license: MPL-2.0
    name: Firefox Sync Server
  2: 
    description: A modern, convivial and free music server
    id: funkwhale
    installed: True
    label: Funkwhale
    license: BSD-3-Clause
    name: Funkwhale
  3: 
    description: Kresus est un outil personnel de gestion de finances.
    id: kresus
    installed: True
    label: Kresus
    license: AGPL-3.0-only
    name: Kresus
  4: 
    description: Mumble est un logiciel libre de voix sur IP (VoIP), son principal usage étant la communication pendant les parties de jeux en réseau.
    id: mumbleserver
    installed: True
    label: Mumble Server
    license: BSD-3-Clause
    name: Mumble Server
  5: 
    description: Mumble est un logiciel libre de voix sur IP (VoIP), son principal usage étant la communication pendant les parties de jeux en réseau.
    id: mumbleserver__2
    installed: True
    label: Mumble Server
    license: BSD-3-Clause
    name: Mumble Server
  6: 
    description: OpenSondage sert à faire des sondages sans authentification pour trouver une date de réunion qui convienne à toutes les personnes concernées.
    id: opensondage
    installed: True
    label: OpenSondage
    license: CECILL-B
    name: OpenSondage
  7: 
    description: Video streaming platform using P2P directly in the web browser, connected to a federated network
    id: peertube
    installed: True
    label: PeerTube
    license: AGPL-3.0-only
    name: PeerTube
  8: 
    description: Federated Image Sharing
    id: pixelfed
    installed: True
    label: Pixelfed
    license: MIT
    name: Pixelfed
  9: 
    description: Créer une redirection ou un proxy vers un autre emplacement
    id: redirect
    installed: True
    label: Redirect
    license: AGPL-3.0-or-later
    name: Redirect
```

I think it's because there is no call to `ynh_webpath_register`

Registering URL add a domain value: https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/app.py#L1138
While listing application through map is filtering: https://github.com/YunoHost/yunohost/blob/stretch-unstable/src/yunohost/app.py#L401
